/* eslint-disable */
// This file is automatically generated or custom-crafted for resilient local fallback.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

class MockSupabaseQuery {
  table: string;
  filters: { [key: string]: any } = {};
  neqFilters: { [key: string]: any } = {};
  isDelete = false;
  isUpsert = false;
  isInsert = false;
  insertData: any = null;

  constructor(table: string) {
    this.table = table;
  }

  select(fields?: string) {
    return this;
  }
  order(col: string, options?: any) {
    return this;
  }
  limit(n: number) {
    return this;
  }

  neq(field: string, val: any) {
    this.neqFilters[field] = val;
    return this;
  }

  eq(field: string, val: any) {
    this.filters[field] = val;
    return this;
  }

  upsert(obj: any) {
    this.isUpsert = true;
    this.insertData = obj;
    return this;
  }

  insert(arr: any[]) {
    this.isInsert = true;
    this.insertData = arr;
    return this;
  }

  delete() {
    this.isDelete = true;
    return this;
  }

  maybeSingle() {
    return this.executeSingle();
  }

  executeSingle() {
    return this.execute().then((res) => {
      const data = res.data;
      return {
        data: data ? (Array.isArray(data) ? data[0] : data) : null,
        error: null,
      };
    });
  }

  execute() {
    const localStorageGet = (key: string) => {
      try {
        return typeof window !== "undefined" ? localStorage.getItem(key) : null;
      } catch {
        return null;
      }
    };
    const localStorageSet = (key: string, val: string) => {
      try {
        if (typeof window !== "undefined") localStorage.setItem(key, val);
      } catch {}
    };

    if (this.table === "manager_messages") {
      let items: any[] = [];
      try {
        const stored = localStorageGet("mock-supabase-messages");
        items = stored ? JSON.parse(stored) : [];
      } catch {}

      if (this.isDelete) {
        items = items.filter((x) => {
          let matchesEq = true;
          for (const [k, v] of Object.entries(this.filters)) {
            if (x[k] !== v) matchesEq = false;
          }
          let matchesNeq = true;
          for (const [k, v] of Object.entries(this.neqFilters)) {
            if (x[k] === v) matchesNeq = false;
          }
          const shouldDelete =
            (Object.keys(this.filters).length > 0 ? matchesEq : true) &&
            (Object.keys(this.neqFilters).length > 0 ? matchesNeq : true);
          return !shouldDelete;
        });
        localStorageSet("mock-supabase-messages", JSON.stringify(items));
        return Promise.resolve({ data: null, error: null });
      }

      if (this.isInsert) {
        const arr = Array.isArray(this.insertData) ? this.insertData : [this.insertData];
        const inserted = arr.map((item) => ({
          id: Math.random().toString(36).substring(7),
          created_at: new Date().toISOString(),
          ...item,
        }));
        items.push(...inserted);
        localStorageSet("mock-supabase-messages", JSON.stringify(items));
        return Promise.resolve({ data: inserted, error: null });
      }

      let filtered = items;
      for (const [k, v] of Object.entries(this.filters)) {
        filtered = filtered.filter((x) => x[k] === v);
      }
      for (const [k, v] of Object.entries(this.neqFilters)) {
        filtered = filtered.filter((x) => x[k] !== v);
      }
      return Promise.resolve({ data: filtered, error: null });
    }

    if (this.table === "league_state") {
      if (this.isUpsert) {
        try {
          localStorageSet("mock-supabase-league-state", JSON.stringify(this.insertData));
        } catch {}
        return Promise.resolve({ data: this.insertData, error: null });
      }
      let stateData = null;
      try {
        const stored = localStorageGet("mock-supabase-league-state");
        stateData = stored ? JSON.parse(stored) : null;
      } catch {}
      return Promise.resolve({ data: stateData, error: null });
    }

    return Promise.resolve({ data: null, error: null });
  }

  then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
    return this.execute().then(onfulfilled, onrejected);
  }
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_ANON_KEY;

  const localClient = {
    from: (table: string) => new MockSupabaseQuery(table),
    channel: (name: string) => ({
      on: (event: string, filter: any, callback: any) => ({
        subscribe: () => {},
      }),
      subscribe: () => {},
    }),
    removeChannel: (channel: any) => Promise.resolve(),
    auth: {
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    },
  } as any;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      "[Supabase] Missing credentials. Falling back to robust localStorage mode for applet execution.",
    );
    return localClient;
  }

  const realClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return {
    ...realClient,
    auth: realClient.auth,
    channel: realClient.channel,
    removeChannel: realClient.removeChannel,
    from: (table: string) => {
      const realQuery = (realClient as any).from(table);
      const mockQuery = new MockSupabaseQuery(table);

      function wrap(realVal: any): any {
        if (!realVal || typeof realVal !== "object") {
          return realVal;
        }

        return new Proxy(realVal, {
          get(target, prop, receiver) {
            if (prop === "then") {
              return (onfulfilled?: any, onrejected?: any) => {
                return target.then(
                  (res: any) => {
                    if (res && res.error) {
                      console.warn(
                        `[Supabase] Real query error on ${table}. Falling back to localStorage.`,
                        res.error.message,
                      );
                      return mockQuery.execute().then(onfulfilled, onrejected);
                    }
                    if (
                      table === "manager_messages" &&
                      res &&
                      Array.isArray(res.data) &&
                      res.data.length === 0
                    ) {
                      return mockQuery.execute().then((mockRes) => {
                        if (mockRes.data && mockRes.data.length > 0) {
                          return onfulfilled ? onfulfilled(mockRes) : mockRes;
                        }
                        return onfulfilled ? onfulfilled(res) : res;
                      });
                    }
                    return onfulfilled ? onfulfilled(res) : res;
                  },
                  (err: any) => {
                    console.warn(
                      `[Supabase] Real query exception on ${table}. Falling back to localStorage.`,
                      err,
                    );
                    return mockQuery.execute().then(onfulfilled, onrejected);
                  },
                );
              };
            }

            if (prop === "maybeSingle") {
              return () => {
                return target.maybeSingle().then(
                  (res: any) => {
                    if (res && res.error) {
                      console.warn(
                        `[Supabase] Real query error on ${table} (maybeSingle). Falling back.`,
                        res.error.message,
                      );
                      return mockQuery.executeSingle();
                    }
                    return res;
                  },
                  (err: any) => {
                    console.warn(
                      `[Supabase] Real query exception on ${table} (maybeSingle). Falling back.`,
                      err,
                    );
                    return mockQuery.executeSingle();
                  },
                );
              };
            }

            const value = Reflect.get(target, prop, receiver);
            if (typeof value === "function") {
              return (...args: any[]) => {
                if (typeof (mockQuery as any)[prop] === "function") {
                  (mockQuery as any)[prop](...args);
                }
                const result = value.apply(target, args);
                return wrap(result);
              };
            }

            return value;
          },
        });
      }

      return wrap(realQuery);
    },
  } as any;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
